services:
  backend-dev:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
      target: dev
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://mashhoodbutt47:masoodbabuak47@cluster0.faqr2tn.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0/product
    depends_on:
      - db

  frontend-dev:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
      target: dev
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_APP_API_URL=https://localhost:5173
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mern_db:/data/db

volumes:
  mern_db:
